#!/usr/bin/env bash

source "${HOME}/personal/productivity/bashqtools/arrayMethods.sh" # get join
source "${HOME}/personal/productivity/paths.sh" #paths

pathsStr=$(join paths ' ')

session=$(find $pathsStr -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)

if [ ! "$TMUX" ]; then
        tmux 
fi
tmux new-session -s "$session_name" -c "$session" -d
tmux switch-client -t "$session_name"
