- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: false
      tags:
      - node
      - zsh
      - nvim
  tasks:
  - name: Download Neovim appimage
    shell: curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    tags:
    - nvim
  - name: grand nvim permission
    shell: chmod u+x nvim.appimage
    tags:
    - nvim
  - name: Download vim plugin manager
    shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    tags:
    - nvim
  - name: install py-venv
    apt: name=python3-venv
    tags:
    - nvim
  - name: install py-pip3
    apt: name=python3-pip
    tags:
    - nvim
  - name: install pip neovim
    pip: name=neovim
    tags:
    - nvim
  - name: install xclip
    apt: name=xclip
    tags:
    - nvim
  - name: make .config dir
    shell: mkdir /root/.config 
    tags:
    - nvim
  - name: clone git repo
    ansible.builtin.git:
      repo: 'https://github.com/pietow/neovim-init.vim.git'
      dest: /root/.config/nvim
    tags:
    - nvim
  - name: Switch branch
    shell: cd /root/.config/nvim && git checkout cleanPlusPlugins && cd ~ 
    tags:
    - nvim
  - name: install nvim plugins
    shell: ./nvim.appimage --appimage-extract-and-run "+silent! PlugInstall!" +qall!
    tags:
    - nvim
  - name: Switch branch
    shell: cd /root/.config/nvim && git checkout LSP-vim && cd ~ 
    tags:
    - nvim
  - name: Install zsh
    apt: name=zsh
    tags:
    - zsh
  - name: Change shell
    shell: chsh -s 'which zsh'
    tags:
    - zsh
  - name: Install ohmyzsh
    shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    tags:
    - zsh
  - name: Install the zsh plugin autosuggestions
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
      dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
      tags:
      - zsh
  - name: Install node
    apt: 
      name: ['nodejs', 'npm']
    tags:
    - node
  - name: Install n
    npm: 
      name: n
      global: true
    tags:
    - node
  - name: n 16
    shell: n 16
    tags:
    - node


